[build]
  publish = "public"

[[redirects]]
  from = "/"
  to = "/tracking.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"
