[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/tracking.html"
  status = 200

# FIX: Redirect da /netlify/functions a /.netlify/functions (CON PUNTO)
[[redirects]]
  from = "/netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# FIX: Anche /api deve puntare a /.netlify/functions (CON PUNTO)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "nft"