[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "nft"

# IMPORTANTE: Redirect da /netlify/functions a /.netlify/functions
[[redirects]]
  from = "/netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Optional: anche per /api/
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200